//
//  QuestionBank.swift
//  ToiecTest
//
//  Created by CNTT-MAC on 6/5/19.
//  Copyright © 2019 Long-TeamDev. All rights reserved.
//

import Foundation


class QuestionBank{
    var list = [QuestionModel]()
    
    init() {
        list.append(QuestionModel(
            question: "Psychiatrists are ridiculed for _ , but new research on genes and the brain suggests they might be right?",
            img: "defautImage",
            answers: [
                Answer(answer: "a mental illness calling every quirk", isRight: true),
                Answer(answer: "a calling for mental illness ever quirk", isRight: false),
                Answer(answer: "calling mental illness an every", isRight: false),
                Answer(answer: "calling mental illness every", isRight: false)
            ]
        ))
        list.append(QuestionModel(
            question: "This Information _ to a great many people?",
            img: "defautImage",
            answers: [
                Answer(answer: "was proved to be useful", isRight: true),
                Answer(answer: "has proved it useful", isRight: false),
                Answer(answer: "has been proved to be useful", isRight: false),
                Answer(answer: "has proved useful", isRight: false)
            ]
        ))
        
        list.append(QuestionModel(
            question: "Psychiatrists are ridiculed for _ , but new research on genes and the brain suggests they might be right?",
            img: "defautImage",
            answers: [
                Answer(answer: "a mental illness calling every quirk", isRight: true),
                Answer(answer: "a calling for mental illness ever quirk", isRight: false),
                Answer(answer: "calling mental illness an every", isRight: false),
                Answer(answer: "calling mental illness every", isRight: false)
            ]
        ))

        list.append(QuestionModel(
            question: "The flamingo uses its bill _feeding to filter mud and water from the tiny plants and animals that it finds in shallow ponds.",
            img: "defautImage",
            answers: [
                Answer(answer: "when", isRight: true),
                Answer(answer: "is", isRight: false),
                Answer(answer: "that it is", isRight: false),
                Answer(answer: "was", isRight: false)
            ]
        ))
        
        list.append(QuestionModel(
            question: "The closer to one of the Earth's poles, the greater _ gravitational force.",
            img: "defautImage",
            answers: [
                Answer(answer: "is", isRight: true),
                Answer(answer: "the", isRight: false),
                Answer(answer: "has", isRight: false),
                Answer(answer: "it has", isRight: false)
            ]
        ))
        
        list.append(QuestionModel(
            question: "After the great blizzard of 1988 in the northeastern United States, it took some _ the snow away from their homes.?",
            img: "defautImage",
            answers: [
                Answer(answer: "days to shovel people several", isRight: true),
                Answer(answer: "people several days to shovel", isRight: false),
                Answer(answer: "several days people to shovel", isRight: false),
                Answer(answer: "people to shovel several days", isRight: false)
            ]
        ))
        list.append(QuestionModel(question: "All the guests _______ home by the time you come to the party. ", img : "defautImage",	answers : [Answer(answer: "have gone ", isRight : true),Answer(answer: "had gone ", isRight : false),Answer(answer: "will go ", isRight : false),Answer(answer: "will have gone", isRight : false)]))
        list.append(QuestionModel(question: "Sorry. I can`t go there with you now. I _________ my homework at present. ", img : "defautImage",	answers : [Answer(answer: "did ", isRight : true),Answer(answer: "do ", isRight : false),Answer(answer: "was doing ", isRight : false),Answer(answer: "am doing", isRight : false)]))
        list.append(QuestionModel(question: "She always _________ dates on the holidays. ", img : "defautImage",	answers : [Answer(answer: "have ", isRight : true),Answer(answer: "had ", isRight : false),Answer(answer: "has had ", isRight : false),Answer(answer: "has", isRight : false)]))
        list.append(QuestionModel(question: "Last year, they _________ to Europe with their best friends on their summer holidays. ", img : "defautImage",	answers : [Answer(answer: "visited ", isRight : true),Answer(answer: "traveled ", isRight : false),Answer(answer: "will travel ", isRight : false),Answer(answer: "are visiting", isRight : false)]))
        list.append(QuestionModel(question: "What are you going to do this weekend?- We _______ visit our grandfather in the countryside. ", img : "defautImage",	answers : [Answer(answer: "are going to ", isRight : true),Answer(answer: "were going to ", isRight : false),Answer(answer: "have gone to ", isRight : false),Answer(answer: "went", isRight : false)]))
        list.append(QuestionModel(question: "Our Singaporean friends_______________ to visit our school last year. ", img : "defautImage",	answers : [Answer(answer: "is coming ", isRight : true),Answer(answer: "come ", isRight : false),Answer(answer: "came ", isRight : false),Answer(answer: "have come", isRight : false)]
        ))
        list.append(QuestionModel(question: "She had to work on _______last night, so she is very tired this morning.", img : "defautImage",	answers : [Answer(answer: "the roof ", isRight : true),Answer(answer: "the table ", isRight : false),Answer(answer: "the bed ", isRight : false),Answer(answer: "night shift ", isRight : false)]))
        list.append(QuestionModel(question: "My father is very busy with his work at the office. He usually comes home very _______at night. ", img : "defautImage",	answers : [Answer(answer: "late ", isRight : true),Answer(answer: "early ", isRight : false),Answer(answer: "on time ", isRight : false),Answer(answer: "past", isRight : false)]))
        list.append(QuestionModel(question: "My mother _______very early in the morning to prepare our breakfast. ", img : "defautImage",	answers : [Answer(answer: "cries ", isRight : true),Answer(answer: "sleeps ", isRight : false),Answer(answer: "gets up ", isRight : false),Answer(answer: "stays up", isRight : false)]))
        list.append(QuestionModel(question: "My mother is a _______woman. She does all the household chores to make us more comfortable. ", img : "defautImage",	answers : [Answer(answer: "caring ", isRight : true),Answer(answer: "careless ", isRight : false),Answer(answer: "harmful ", isRight : false),Answer(answer: "boring", isRight : false)]))
        list.append(QuestionModel(question: "In my free-time, I often help mom with _______the house. ", img : "defautImage",	answers : [Answer(answer: "to clean ", isRight : true),Answer(answer: "clean ", isRight : false),Answer(answer: "cleaning ", isRight : false),Answer(answer: "cleans", isRight : false)]))
        list.append(QuestionModel(question: "I take responsibility to _______my little brothers because they are sometimes very naughty. ", img : "defautImage",	answers : [Answer(answer: "look after ", isRight : true),Answer(answer: "get up ", isRight : false),Answer(answer: "sit down ", isRight : false),Answer(answer: "shut up ", isRight : false)]))
        list.append(QuestionModel(question: "My responsibility is to wash dishes and _______the garbage. ", img : "defautImage",	answers : [Answer(answer: "take off ", isRight : true),Answer(answer: "take out ", isRight : false),Answer(answer: "take care of ", isRight : false),Answer(answer: "take over", isRight : false)]))
        list.append(QuestionModel(question: "My brothers love joining my dad in _______things around the house at weekends. ", img : "defautImage",	answers : [Answer(answer: "mend ", isRight : true),Answer(answer: "mended ", isRight : false),Answer(answer: "to mend ", isRight : false),Answer(answer: "mending", isRight : false)]))
        list.append(QuestionModel(question: "Whenever problems come up, we discuss frankly and find _______quickly. ", img : "defautImage",	answers : [Answer(answer: "solve ", isRight : true),Answer(answer: "solution ", isRight : false),Answer(answer: "solved ", isRight : false),Answer(answer: "to solve", isRight : false)]))
        list.append(QuestionModel(question: "Mai is my closest frienWe are always willing to _______feelings to each other. ", img : "defautImage",	answers : [Answer(answer: "tear ", isRight : true),Answer(answer: "cut ", isRight : false),Answer(answer: "share ", isRight : false),Answer(answer: "shake", isRight : false)]))
        list.append(QuestionModel(question: "My family is the base from which we can go into the world with _______. ", img : "defautImage",	answers : [Answer(answer: "confide ", isRight : true),Answer(answer: "confidence ", isRight : false),Answer(answer: "confident ", isRight : false),Answer(answer: "confiding", isRight : false)]))
        list.append(QuestionModel(question: "I like doing _______such as cooking, washing and cleaning the house. ", img : "defautImage",	answers : [Answer(answer: "house-keeper ", isRight : true),Answer(answer: "white house ", isRight : false),Answer(answer: "lord of house ", isRight : false),Answer(answer: "household chores", isRight : false)]))
        list.append(QuestionModel(question: "My father is a _______He often does researches with animals and plants. ", img : "defautImage",	answers : [Answer(answer: "botanist ", isRight : true),Answer(answer: "biologist ", isRight : false),Answer(answer: "chemist ", isRight : false),Answer(answer: "mathematician", isRight : false)]))
        list.append(QuestionModel(question: "In my family, both my parents _______to give us a nice house and a happy home. ", img : "defautImage",	answers : [Answer(answer: "join hands ", isRight : true),Answer(answer: "get out ", isRight : false),Answer(answer: "shake hands ", isRight : false),Answer(answer: "clutch hands", isRight : false)]))
        list.append(QuestionModel(question: "My brothers are often very _______to what I say. They are really lovable. ", img : "defautImage",	answers : [Answer(answer: "obey ", isRight : true),Answer(answer: "obedience ", isRight : false),Answer(answer: "obedient ", isRight : false),Answer(answer: "obstacle", isRight : false)]))
        list.append(QuestionModel(question: "Unlike most men, my uncle likes _______very much. I like his eel soup very much. ", img : "defautImage",	answers : [Answer(answer: "having a shower ", isRight : true),Answer(answer: "drinking beer ", isRight : false),Answer(answer: "playing cards ", isRight : false),Answer(answer: "cooking ", isRight : false)]))
        list.append(QuestionModel(question: "My responsibility is to _______my little brothers. ", img : "defautImage",	answers : [Answer(answer: "take care of ", isRight : true),Answer(answer: "join hands ", isRight : false),Answer(answer: "take over ", isRight : false),Answer(answer: "work together", isRight : false)]))
        list.append(QuestionModel(question: "Although my father is very busy, he tries _______much time taking care of his children. ", img : "defautImage",	answers : [Answer(answer: "to spend ", isRight : true),Answer(answer: "spending ", isRight : false),Answer(answer: "to get up ", isRight : false),Answer(answer: "getting up", isRight : false)]))
        list.append(QuestionModel(question: "My father is very helpful. He is always _______give a hand with cleaning the house. ", img : "defautImage",	answers : [Answer(answer: "will to ", isRight : true),Answer(answer: "will ", isRight : false),Answer(answer: "willing ", isRight : false),Answer(answer: "willing to", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "proofs ", isRight : true),Answer(answer: "books ", isRight : false),Answer(answer: "points ", isRight : false),Answer(answer: "days", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "helps ", isRight : true),Answer(answer: "laughs ", isRight : false),Answer(answer: "cooks ", isRight : false),Answer(answer: "finds", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "neighbors ", isRight : true),Answer(answer: "friends ", isRight : false),Answer(answer: "relatives ", isRight : false),Answer(answer: "photographs", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "snacks ", isRight : true),Answer(answer: "follows ", isRight : false),Answer(answer: "titles ", isRight : false),Answer(answer: "writers", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "streets ", isRight : true),Answer(answer: "phones ", isRight : false),Answer(answer: "books ", isRight : false),Answer(answer: "makes", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "cities ", isRight : true),Answer(answer: "satellites ", isRight : false),Answer(answer: "series ", isRight : false),Answer(answer: "workers", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "develops ", isRight : true),Answer(answer: "takes ", isRight : false),Answer(answer: "laughs ", isRight : false),Answer(answer: "volumes", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "phones ", isRight : true),Answer(answer: "streets ", isRight : false),Answer(answer: "books ", isRight : false),Answer(answer: "makes", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "proofs ", isRight : true),Answer(answer: "regions ", isRight : false),Answer(answer: "lifts ", isRight : false),Answer(answer: "rocks", isRight : false)]))
        list.append(QuestionModel(question: "My mother works _______a nurse in a big hospital. She examines the patients.", img : "defautImage",	answers : [Answer(answer: "for ", isRight : true),Answer(answer: "as ", isRight : false),Answer(answer: "in ", isRight : false),Answer(answer: "at", isRight : false)]))
        list.append(QuestionModel(question: "She had to work on _______last night, so she is very tired this morning.", img : "defautImage",	answers : [Answer(answer: "the roof ", isRight : true),Answer(answer: "the table ", isRight : false),Answer(answer: "the bed ", isRight : false),Answer(answer: "night shift ", isRight : false)]))
        list.append(QuestionModel(question: "My father is very busy with his work at the office. He usually comes home very _______at night. ", img : "defautImage",	answers : [Answer(answer: "late ", isRight : true),Answer(answer: "early ", isRight : false),Answer(answer: "on time ", isRight : false),Answer(answer: "past", isRight : false)]))
        list.append(QuestionModel(question: "My mother _______very early in the morning to prepare our breakfast. ", img : "defautImage",	answers : [Answer(answer: "cries ", isRight : true),Answer(answer: "sleeps ", isRight : false),Answer(answer: "gets up ", isRight : false),Answer(answer: "stays up", isRight : false)]))
        list.append(QuestionModel(question: "My mother is a _______woman. She does all the household chores to make us more comfortable. ", img : "defautImage",	answers : [Answer(answer: "caring ", isRight : true),Answer(answer: "careless ", isRight : false),Answer(answer: "harmful ", isRight : false),Answer(answer: "boring", isRight : false)]))
        list.append(QuestionModel(question: "In my free-time, I often help mom with _______the house. ", img : "defautImage",	answers : [Answer(answer: "to clean ", isRight : true),Answer(answer: "clean ", isRight : false),Answer(answer: "cleaning ", isRight : false),Answer(answer: "cleans", isRight : false)]))
        list.append(QuestionModel(question: "I take responsibility to _______my little brothers because they are sometimes very naughty. ", img : "defautImage",	answers : [Answer(answer: "look after ", isRight : true),Answer(answer: "get up ", isRight : false),Answer(answer: "sit down ", isRight : false),Answer(answer: "shut up ", isRight : false)]))
        list.append(QuestionModel(question: "My responsibility is to wash dishes and _______the garbage. ", img : "defautImage",	answers : [Answer(answer: "take off ", isRight : true),Answer(answer: "take out ", isRight : false),Answer(answer: "take care of ", isRight : false),Answer(answer: "take over", isRight : false)]))
        list.append(QuestionModel(question: "My brothers love joining my dad in _______things around the house at weekends. ", img : "defautImage",	answers : [Answer(answer: "mend ", isRight : true),Answer(answer: "mended ", isRight : false),Answer(answer: "to mend ", isRight : false),Answer(answer: "mending", isRight : false)]))
        list.append(QuestionModel(question: "Whenever problems come up, we discuss frankly and find _______quickly. ", img : "defautImage",	answers : [Answer(answer: "solve ", isRight : true),Answer(answer: "solution ", isRight : false),Answer(answer: "solved ", isRight : false),Answer(answer: "to solve", isRight : false)]))
        list.append(QuestionModel(question: "Mai is my closest frienWe are always willing to _______feelings to each other. ", img : "defautImage",	answers : [Answer(answer: "tear ", isRight : true),Answer(answer: "cut ", isRight : false),Answer(answer: "share ", isRight : false),Answer(answer: "shake", isRight : false)]))
        list.append(QuestionModel(question: "My family is the base from which we can go into the world with _______. ", img : "defautImage",	answers : [Answer(answer: "confide ", isRight : true),Answer(answer: "confidence ", isRight : false),Answer(answer: "confident ", isRight : false),Answer(answer: "confiding", isRight : false)]))
        list.append(QuestionModel(question: "I like doing _______such as cooking, washing and cleaning the house. ", img : "defautImage",	answers : [Answer(answer: "house-keeper ", isRight : true),Answer(answer: "white house ", isRight : false),Answer(answer: "lord of house ", isRight : false),Answer(answer: "household chores", isRight : false)]))
        list.append(QuestionModel(question: "My father is a _______He often does researches with animals and plants. ", img : "defautImage",	answers : [Answer(answer: "botanist ", isRight : true),Answer(answer: "biologist ", isRight : false),Answer(answer: "chemist ", isRight : false),Answer(answer: "mathematician", isRight : false)]))
        list.append(QuestionModel(question: "In my family, both my parents _______to give us a nice house and a happy home. ", img : "defautImage",	answers : [Answer(answer: "join hands ", isRight : true),Answer(answer: "get out ", isRight : false),Answer(answer: "shake hands ", isRight : false),Answer(answer: "clutch hands", isRight : false)]))
        list.append(QuestionModel(question: "My brothers are often very _______to what I say. They are really lovable. ", img : "defautImage",	answers : [Answer(answer: "obey ", isRight : true),Answer(answer: "obedience ", isRight : false),Answer(answer: "obedient ", isRight : false),Answer(answer: "obstacle", isRight : false)]))
        list.append(QuestionModel(question: "Unlike most men, my uncle likes _______very much. I like his eel soup very much. ", img : "defautImage",	answers : [Answer(answer: "having a shower ", isRight : true),Answer(answer: "drinking beer ", isRight : false),Answer(answer: "playing cards ", isRight : false),Answer(answer: "cooking ", isRight : false)]))
        list.append(QuestionModel(question: "My responsibility is to _______my little brothers. ", img : "defautImage",	answers : [Answer(answer: "take care of ", isRight : true),Answer(answer: "join hands ", isRight : false),Answer(answer: "take over ", isRight : false),Answer(answer: "work together", isRight : false)]))
        list.append(QuestionModel(question: "Although my father is very busy, he tries _______much time taking care of his children. ", img : "defautImage",	answers : [Answer(answer: "to spend ", isRight : true),Answer(answer: "spending ", isRight : false),Answer(answer: "to get up ", isRight : false),Answer(answer: "getting up", isRight : false)]))
        list.append(QuestionModel(question: "My father is very helpful. He is always _______give a hand with cleaning the house. ", img : "defautImage",	answers : [Answer(answer: "will to ", isRight : true),Answer(answer: "will ", isRight : false),Answer(answer: "willing ", isRight : false),Answer(answer: "willing to", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "proofs ", isRight : true),Answer(answer: "books ", isRight : false),Answer(answer: "points ", isRight : false),Answer(answer: "days", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "helps ", isRight : true),Answer(answer: "laughs ", isRight : false),Answer(answer: "cooks ", isRight : false),Answer(answer: "finds", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "neighbors ", isRight : true),Answer(answer: "friends ", isRight : false),Answer(answer: "relatives ", isRight : false),Answer(answer: "photographs", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "snacks ", isRight : true),Answer(answer: "follows ", isRight : false),Answer(answer: "titles ", isRight : false),Answer(answer: "writers", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "streets ", isRight : true),Answer(answer: "phones ", isRight : false),Answer(answer: "books ", isRight : false),Answer(answer: "makes", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "cities ", isRight : true),Answer(answer: "satellites ", isRight : false),Answer(answer: "series ", isRight : false),Answer(answer: "workers", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "develops ", isRight : true),Answer(answer: "takes ", isRight : false),Answer(answer: "laughs ", isRight : false),Answer(answer: "volumes", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "phones ", isRight : true),Answer(answer: "streets ", isRight : false),Answer(answer: "books ", isRight : false),Answer(answer: "makes", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "proofs ", isRight : true),Answer(answer: "regions ", isRight : false),Answer(answer: "lifts ", isRight : false),Answer(answer: "rocks", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "involves ", isRight : true),Answer(answer: "believes ", isRight : false),Answer(answer: "suggests ", isRight : false),Answer(answer: "steals", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "remembers ", isRight : true),Answer(answer: "cooks ", isRight : false),Answer(answer: "walls ", isRight : false),Answer(answer: "pyramids", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "miles ", isRight : true),Answer(answer: "words ", isRight : false),Answer(answer: "accidents ", isRight : false),Answer(answer: "names", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "sports ", isRight : true),Answer(answer: "plays ", isRight : false),Answer(answer: "chores ", isRight : false),Answer(answer: "minds", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "nations ", isRight : true),Answer(answer: "speakers ", isRight : false),Answer(answer: "languages ", isRight : false),Answer(answer: "minds", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "proofs ", isRight : true),Answer(answer: "looks ", isRight : false),Answer(answer: "lends ", isRight : false),Answer(answer: "stops", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "dates ", isRight : true),Answer(answer: "bags ", isRight : false),Answer(answer: "photographs ", isRight : false),Answer(answer: "speaks", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "parents ", isRight : true),Answer(answer: "brothers ", isRight : false),Answer(answer: "weekends ", isRight : false),Answer(answer: "feelings", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "chores ", isRight : true),Answer(answer: "dishes ", isRight : false),Answer(answer: "houses ", isRight : false),Answer(answer: "coaches", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "works ", isRight : true),Answer(answer: "shops ", isRight : false),Answer(answer: "shifts ", isRight : false),Answer(answer: "plays", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "coughs ", isRight : true),Answer(answer: "sings ", isRight : false),Answer(answer: "stops ", isRight : false),Answer(answer: "sleeps", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "signs ", isRight : true),Answer(answer: "profits ", isRight : false),Answer(answer: "becomes ", isRight : false),Answer(answer: "survives", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "walks ", isRight : true),Answer(answer: "steps ", isRight : false),Answer(answer: "shuts ", isRight : false),Answer(answer: "plays", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "wishes ", isRight : true),Answer(answer: "practices ", isRight : false),Answer(answer: "introduces ", isRight : false),Answer(answer: "leaves", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "grasses ", isRight : true),Answer(answer: "stretches ", isRight : false),Answer(answer: "comprises ", isRight : false),Answer(answer: "potatoes", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "desks ", isRight : true),Answer(answer: "maps ", isRight : false),Answer(answer: "plants ", isRight : false),Answer(answer: "chairs", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "pens ", isRight : true),Answer(answer: "books ", isRight : false),Answer(answer: "phones ", isRight : false),Answer(answer: "tables", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "dips ", isRight : true),Answer(answer: "deserts ", isRight : false),Answer(answer: "books ", isRight : false),Answer(answer: "camels", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "miles ", isRight : true),Answer(answer: "attends ", isRight : false),Answer(answer: "drifts ", isRight : false),Answer(answer: "glows", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "mends ", isRight : true),Answer(answer: "develops ", isRight : false),Answer(answer: "values ", isRight : false),Answer(answer: "equals", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "repeats ", isRight : true),Answer(answer: "classmates ", isRight : false),Answer(answer: "amuses ", isRight : false),Answer(answer: "attacks", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "humans ", isRight : true),Answer(answer: "dreams ", isRight : false),Answer(answer: "concerts ", isRight : false),Answer(answer: "songs", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "manages ", isRight : true),Answer(answer: "laughs ", isRight : false),Answer(answer: "photographs ", isRight : false),Answer(answer: "makes", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "dishes ", isRight : true),Answer(answer: "oranges ", isRight : false),Answer(answer: "experiences ", isRight : false),Answer(answer: "chores", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "fills ", isRight : true),Answer(answer: "adds ", isRight : false),Answer(answer: "stirs ", isRight : false),Answer(answer: "lets", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "wants ", isRight : true),Answer(answer: "books ", isRight : false),Answer(answer: "stops ", isRight : false),Answer(answer: "sends", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "books ", isRight : true),Answer(answer: "dogs ", isRight : false),Answer(answer: "cats ", isRight : false),Answer(answer: "maps", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "biscuits ", isRight : true),Answer(answer: "magazines ", isRight : false),Answer(answer: "newspapers ", isRight : false),Answer(answer: "vegetables", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "knees ", isRight : true),Answer(answer: "peas ", isRight : false),Answer(answer: "trees ", isRight : false),Answer(answer: "niece", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "cups ", isRight : true),Answer(answer: "stamps ", isRight : false),Answer(answer: "books ", isRight : false),Answer(answer: "pens", isRight : false)]))
        list.append(QuestionModel(question: "Please select a word with an underlined section that has a different pronunciation than the other words ", img : "defautImage",	answers : [Answer(answer: "houses ", isRight : true),Answer(answer: "faces ", isRight : false),Answer(answer: "hates ", isRight : false),Answer(answer: "places", isRight : false)]))
        list.append(QuestionModel(question: "He has lived here since he ________ here. ", img : "defautImage",	answers : [Answer(answer: "came ", isRight : true),Answer(answer: "has came ", isRight : false),Answer(answer: "comes ", isRight : false),Answer(answer: "come", isRight : false)]))
        list.append(QuestionModel(question: "John________ as a journalist since he ________ from university in 2000. ", img : "defautImage",	answers : [Answer(answer: "is working / graduate ", isRight : true),Answer(answer: "worked / graduated ", isRight : false),Answer(answer: "had worked / will be graduate ", isRight : false),Answer(answer: "has been working / graduated ", isRight : false)]))
        list.append(QuestionModel(question: "He does not save as much money as he________ last year. ", img : "defautImage",	answers : [Answer(answer: "did ", isRight : true),Answer(answer: "does ", isRight : false),Answer(answer: "uses ", isRight : false),Answer(answer: "did used ", isRight : false)]))
        list.append(QuestionModel(question: "She has not written to me________ we met last time. ", img : "defautImage",	answers : [Answer(answer: "before", isRight : true),Answer(answer: "since ", isRight : false),Answer(answer: "ago ", isRight : false),Answer(answer: "meanwhile ", isRight : false)]))
        list.append(QuestionModel(question: "The police ________ for the thieves at the moment. ", img : "defautImage",	answers : [Answer(answer: "have been looking ", isRight : true),Answer(answer: "will be looking ", isRight : false),Answer(answer: "are looking ", isRight : false),Answer(answer: "is looking ", isRight : false)]))
        list.append(QuestionModel(question: "Put the raincoat on. It________. ", img : "defautImage",	answers : [Answer(answer: "had rained ", isRight : true),Answer(answer: "will be raining ", isRight : false),Answer(answer: "is raining ", isRight : false),Answer(answer: "has rained ", isRight : false)]))
        list.append(QuestionModel(question: "Since motion pictures________ we have had a new kind of entertainment. ", img : "defautImage",	answers : [Answer(answer: "were invented ", isRight : true),Answer(answer: "have been invented ", isRight : false),Answer(answer: "will have been invented ", isRight : false),Answer(answer: "had been invented ", isRight : false)]))
        list.append(QuestionModel(question: "There________ a lot of furniture in our uncle`s house now. ", img : "defautImage",	answers : [Answer(answer: "is being ", isRight : true),Answer(answer: "were ", isRight : false),Answer(answer: "are ", isRight : false),Answer(answer: "is ", isRight : false)]))
        list.append(QuestionModel(question: "Mr. Jones sometimes________ on time for work. ", img : "defautImage",	answers : [Answer(answer: "does not get up ", isRight : true),Answer(answer: "won`t get up ", isRight : false),Answer(answer: "had not got up ", isRight : false),Answer(answer: "is not going to get up ", isRight : false)]))
        list.append(QuestionModel(question: "He ________ for twenty years before he retired last year", img : "defautImage",	answers : [Answer(answer: "had been teaching ", isRight : true),Answer(answer: "has taught ", isRight : false),Answer(answer: "was teaching ", isRight : false),Answer(answer: "has been teaching", isRight : false)]))
        list.append(QuestionModel(question: "He said that everything ________ all right ", img : "defautImage",	answers : [Answer(answer: "is ", isRight : true),Answer(answer: "would be ", isRight : false),Answer(answer: "will be ", isRight : false),Answer(answer: "can be", isRight : false)]))
        list.append(QuestionModel(question: "Each of you ________ a share in the work", img : "defautImage",	answers : [Answer(answer: "have ", isRight : true),Answer(answer: "having ", isRight : false),Answer(answer: "has ", isRight : false),Answer(answer: "going to have", isRight : false)]))
        list.append(QuestionModel(question: "How many times________ them so far?", img : "defautImage",	answers : [Answer(answer: "have you seen ", isRight : true),Answer(answer: "did you see ", isRight : false),Answer(answer: "were you seeing ", isRight : false),Answer(answer: "had you seen", isRight : false)]))
        list.append(QuestionModel(question: "Please send our regards to Tom as soon as you ________ in New York. ", img : "defautImage",	answers : [Answer(answer: "will arrive ", isRight : true),Answer(answer: "is going to arrive ", isRight : false),Answer(answer: "arrive ", isRight : false),Answer(answer: "arrived", isRight : false)]))
        list.append(QuestionModel(question: "By the time the ambulance approached, the man________. ", img : "defautImage",	answers : [Answer(answer: "would die ", isRight : true),Answer(answer: "had died ", isRight : false),Answer(answer: "died ", isRight : false),Answer(answer: "dies", isRight : false)]))
        list.append(QuestionModel(question: "We________ for going home when it began to rain", img : "defautImage",	answers : [Answer(answer: "has prepared ", isRight : true),Answer(answer: "are preparing ", isRight : false),Answer(answer: "will be preparing ", isRight : false),Answer(answer: "were preparing", isRight : false)]))
        list.append(QuestionModel(question: "I haven`t seen him for months. ", img : "defautImage",	answers : [Answer(answer: "It`s months since I last saw him ", isRight : true),Answer(answer: "It`s months when I last saw him", isRight : false),Answer(answer: "It`s months before I last saw him ", isRight : false),Answer(answer: "It`s months after I last saw him", isRight : false)]))
        list.append(QuestionModel(question: "Tim________ his hair while I ________ up the kitchen", img : "defautImage",	answers : [Answer(answer: "washed-was cleaned ", isRight : true),Answer(answer: "was washing-was cleaning", isRight : false),Answer(answer: "was washing-cleaned ", isRight : false),Answer(answer: "washed-cleaned", isRight : false)]))
        list.append(QuestionModel(question: "Working for 12 hours a day ________ her very tire", img : "defautImage",	answers : [Answer(answer: "makes ", isRight : true),Answer(answer: "made ", isRight : false),Answer(answer: "make ", isRight : false),Answer(answer: "making", isRight : false)]))
        list.append(QuestionModel(question: "I am so happy to hear from Mary because I haven`t seen her ________ last year. ", img : "defautImage",	answers : [Answer(answer: "for ", isRight : true),Answer(answer: "on ", isRight : false),Answer(answer: "since ", isRight : false),Answer(answer: "later", isRight : false)]))
        list.append(QuestionModel(question: "As she ________ a letter last night, the lights suddenly ________ out. ", img : "defautImage",	answers : [Answer(answer: "was writing/ went ", isRight : true),Answer(answer: "wrote/ went", isRight : false),Answer(answer: "was writing/ was going ", isRight : false),Answer(answer: "writes/ went", isRight : false)]))
        list.append(QuestionModel(question: "How ________ since we ________ school?", img : "defautImage",	answers : [Answer(answer: "are you/ left ", isRight : true),Answer(answer: "will you be/ had left", isRight : false),Answer(answer: "have you been/ had left ", isRight : false),Answer(answer: "have you been / left", isRight : false)]))
        list.append(QuestionModel(question: "I ________ my uncle`s home many times when I ________ a chil", img : "defautImage",	answers : [Answer(answer: "visited/ is ", isRight : true),Answer(answer: "visits/ was ", isRight : false),Answer(answer: "visited/ was ", isRight : false),Answer(answer: "visited/ were", isRight : false)]))
        list.append(QuestionModel(question: "It ________ me half an hour to get to the supermarket yesterday. ", img : "defautImage",	answers : [Answer(answer: "take ", isRight : true),Answer(answer: "takes ", isRight : false),Answer(answer: "took ", isRight : false),Answer(answer: "spent", isRight : false)]))
        list.append(QuestionModel(question: "If I were you, I ________ him as my nephew. ", img : "defautImage",	answers : [Answer(answer: "will treat ", isRight : true),Answer(answer: "would treat ", isRight : false),Answer(answer: "will have treated ", isRight : false),Answer(answer: "am treating", isRight : false)]))
        list.append(QuestionModel(question: "I can`t believe that my expensive bicycle ________ last night. ", img : "defautImage",	answers : [Answer(answer: "was stolen ", isRight : true),Answer(answer: "was stealing ", isRight : false),Answer(answer: "is stolen ", isRight : false),Answer(answer: "stole", isRight : false)]))
        list.append(QuestionModel(question: "I ________ here for more than 10 years. ", img : "defautImage",	answers : [Answer(answer: "have taught ", isRight : true),Answer(answer: "taught ", isRight : false),Answer(answer: "teach ", isRight : false),Answer(answer: "is teaching ", isRight : false)]))
        list.append(QuestionModel(question: "As I ________ my homework, he came yesterday afternoon. ", img : "defautImage",	answers : [Answer(answer: "did ", isRight : true),Answer(answer: "were doing ", isRight : false),Answer(answer: "am doing ", isRight : false),Answer(answer: "was doing", isRight : false)]))
        list.append(QuestionModel(question: "At this time yesterday, everyone ________. in the room. ", img : "defautImage",	answers : [Answer(answer: "is dancing ", isRight : true),Answer(answer: "was dancing ", isRight : false),Answer(answer: "dances ", isRight : false),Answer(answer: "danced", isRight : false)]))
        list.append(QuestionModel(question: "After Mary________ her degree, she intends to work in her father`s company. ", img : "defautImage",	answers : [Answer(answer: "will finish ", isRight : true),Answer(answer: "is finishing ", isRight : false),Answer(answer: "finishes ", isRight : false),Answer(answer: "will have finished", isRight : false)]))
        list.append(QuestionModel(question: "A small stone struck the windshield while we ________ down the roa", img : "defautImage",	answers : [Answer(answer: "drive ", isRight : true),Answer(answer: "were driving ", isRight : false),Answer(answer: "had driven ", isRight : false),Answer(answer: "had been driving", isRight : false)]))
        list.append(QuestionModel(question: "Mr. Hân is going to the USA for his holiday. He ________ up for nearly a year now. ", img : "defautImage",	answers : [Answer(answer: "has saved ", isRight : true),Answer(answer: "is saving ", isRight : false),Answer(answer: "saves ", isRight : false),Answer(answer: "has been saving", isRight : false)]))
        list.append(QuestionModel(question: "The carpet ________. ", img : "defautImage",	answers : [Answer(answer: "hasn`t been cleaned yet. ", isRight : true),Answer(answer: "hasn`t cleaned yet. ", isRight : false),Answer(answer: "have yet been cleane", isRight : false),Answer(answer: "has cleane", isRight : false)]))
        list.append(QuestionModel(question: "Did you have a good time abroad? - She asked me if ________. ", img : "defautImage",	answers : [Answer(answer: "I have a good time abroa", isRight : true),Answer(answer: "I had good time abroa", isRight : false),Answer(answer: "I had had a good time abroa", isRight : false),Answer(answer: "I have had a good time abroa", isRight : false)]))
        list.append(QuestionModel(question: "________ this letter ________ last night?", img : "defautImage",	answers : [Answer(answer: "Is/ written ", isRight : true),Answer(answer: "Is/ wrote ", isRight : false),Answer(answer: "Was/ written ", isRight : false),Answer(answer: "Were/ written", isRight : false)]))
        list.append(QuestionModel(question: "The houses where I used to live ________ very comfortable. ", img : "defautImage",	answers : [Answer(answer: "is ", isRight : true),Answer(answer: "was ", isRight : false),Answer(answer: "are ", isRight : false),Answer(answer: "were", isRight : false)]))
        list.append(QuestionModel(question: "After he ________ English course, he went to England to continue his study. ", img : "defautImage",	answers : [Answer(answer: "will finish ", isRight : true),Answer(answer: "has finished ", isRight : false),Answer(answer: "had finished ", isRight : false),Answer(answer: "have been finished ", isRight : false)]))
        list.append(QuestionModel(question: "I wish I ________ a trip to London last year. ", img : "defautImage",	answers : [Answer(answer: "had taken ", isRight : true),Answer(answer: "took ", isRight : false),Answer(answer: "will take ", isRight : false),Answer(answer: "take", isRight : false)]))
        list.append(QuestionModel(question: "He started living here three years ago. ", img : "defautImage",	answers : [Answer(answer: "He lived here three years ago. ", isRight : true),Answer(answer: "He has lived here for three years. ", isRight : false),Answer(answer: "He had been living here for three years. ", isRight : false),Answer(answer: "He had lived here three years ago. ", isRight : false)]))
        list.append(QuestionModel(question: "Who ________ when I came?", img : "defautImage",	answers : [Answer(answer: "were you talking to ", isRight : true),Answer(answer: "are you talking to ", isRight : false),Answer(answer: "you are talking to ", isRight : false),Answer(answer: "you were talking to", isRight : false)]))
        list.append(QuestionModel(question: "Please send us a post card as soon as you ________ in London. ", img : "defautImage",	answers : [Answer(answer: "will arrive ", isRight : true),Answer(answer: "is going to arrive ", isRight : false),Answer(answer: "arrive ", isRight : false),Answer(answer: "arrived", isRight : false)]))
        list.append(QuestionModel(question: "Now he ________ a book about English. I don`t think he will finish it. ", img : "defautImage",	answers : [Answer(answer: "writes ", isRight : true),Answer(answer: "wrote ", isRight : false),Answer(answer: "has written ", isRight : false),Answer(answer: "is writing", isRight : false)]))
        list.append(QuestionModel(question: "The foreign guest ________ here almost a week. ", img : "defautImage",	answers : [Answer(answer: "was ", isRight : true),Answer(answer: "are ", isRight : false),Answer(answer: "has been ", isRight : false),Answer(answer: "is", isRight : false)]))
        list.append(QuestionModel(question: "Look! The two boys ________ your window. ", img : "defautImage",	answers : [Answer(answer: "were painting ", isRight : true),Answer(answer: "painting ", isRight : false),Answer(answer: "are painting ", isRight : false),Answer(answer: "have painted", isRight : false)]))
        list.append(QuestionModel(question: "Before he ________ to bed, he ________ his homework. ", img : "defautImage",	answers : [Answer(answer: "went/ has done ", isRight : true),Answer(answer: "went/ had done ", isRight : false),Answer(answer: "goes/ have done ", isRight : false),Answer(answer: "goes/ did", isRight : false)]))
        list.append(QuestionModel(question: "He is the most wonderful person I ________. ", img : "defautImage",	answers : [Answer(answer: "have ever met ", isRight : true),Answer(answer: "had ever met ", isRight : false),Answer(answer: "ever meet ", isRight : false),Answer(answer: "am meeting", isRight : false)]))
        list.append(QuestionModel(question: "Millions of dollars ________ spent on advertising every year. ", img : "defautImage",	answers : [Answer(answer: "is ", isRight : true),Answer(answer: "was ", isRight : false),Answer(answer: "are ", isRight : false),Answer(answer: "were", isRight : false)]))
        list.append(QuestionModel(question: "I haven`t seen him for ages. ", img : "defautImage",	answers : [Answer(answer: "It`s ages since I last saw him. ", isRight : true),Answer(answer: "It`s ages when I last saw him. ", isRight : false),Answer(answer: "It`s ages before I last saw him. ", isRight : false),Answer(answer: "It`s ages after I last saw him. ", isRight : false)]))
        list.append(QuestionModel(question: "He found a watch in the street, and then he ________ to return it to the loser. ", img : "defautImage",	answers : [Answer(answer: "had tried ", isRight : true),Answer(answer: "was trying ", isRight : false),Answer(answer: "tried ", isRight : false),Answer(answer: "had been trying", isRight : false)]))
        list.append(QuestionModel(question: "If he ________ for the revision session, he might have no difficulty doing the test right now. ", img : "defautImage",	answers : [Answer(answer: "had come ", isRight : true),Answer(answer: "came ", isRight : false),Answer(answer: "is to come ", isRight : false),Answer(answer: "had to come", isRight : false)]))
        list.append(QuestionModel(question: "I / finish / read / long novel / Arthur Hailey //", img : "defautImage",	answers : [Answer(answer: "I finished to read a long novel of Arthur Hailey. ", isRight : true),Answer(answer: "I`ve just finished reading a long novel written by Arthur Hailey. ", isRight : false),Answer(answer: "I`ve finished reading the long Arthur Hailey`s novel. ", isRight : false),Answer(answer: "I finished the reading long novel with Arthur Hailey", isRight : false)]))
        list.append(QuestionModel(question: "throw / thousands / tons / rubbish / forest / year //", img : "defautImage",	answers : [Answer(answer: "People throw some thousands tons of rubbish into the forest every year. ", isRight : true),Answer(answer: "People throw thousands of tons of rubbish into the forest every year. ", isRight : false),Answer(answer: "Throwing thousands of tons of rubbish is into the forest every year. ", isRight : false),Answer(answer: "People throwing thousands of tons of rubbishes into the forest every year. ", isRight : false)]))
        list.append(QuestionModel(question: "The Magic Hat __________ at 12A.M every Saturday. ", img : "defautImage",	answers : [Answer(answer: "broadcast ", isRight : true),Answer(answer: "broadcasts ", isRight : false),Answer(answer: "is broadcasting ", isRight : false),Answer(answer: "broadcasted", isRight : false)]))
        list.append(QuestionModel(question: "The whistle signaled the end of the first half. The match will continue after half-time and now AC Milan ___________ Juventus by 2 goals to nil. ", img : "defautImage",	answers : [Answer(answer: "led ", isRight : true),Answer(answer: "is leading ", isRight : false),Answer(answer: "has led ", isRight : false),Answer(answer: "leads", isRight : false)]))
        list.append(QuestionModel(question: "_________ any letters from him lately?", img : "defautImage",	answers : [Answer(answer: "Do you receive ", isRight : true),Answer(answer: "Have you received ", isRight : false),Answer(answer: "Are you receiving ", isRight : false),Answer(answer: "Had you received", isRight : false)]))
        list.append(QuestionModel(question: "I _________ a meeting at the office at this time tomorrow, so you can phone me later in the evening. ", img : "defautImage",	answers : [Answer(answer: "have ", isRight : true),Answer(answer: "have had ", isRight : false),Answer(answer: "will have had ", isRight : false),Answer(answer: "will be having", isRight : false)]))
        list.append(QuestionModel(question: "The moon __________ around the earth. ", img : "defautImage",	answers : [Answer(answer: "has moved ", isRight : true),Answer(answer: "moves ", isRight : false),Answer(answer: "is moving ", isRight : false),Answer(answer: "will move", isRight : false)]))
        list.append(QuestionModel(question: "She said she __________ that film years before. ", img : "defautImage",	answers : [Answer(answer: "saw ", isRight : true),Answer(answer: "has seen ", isRight : false),Answer(answer: "had seen ", isRight : false),Answer(answer: "would see", isRight : false)]))
        list.append(QuestionModel(question: "The film will end when you have finished dinner. ", img : "defautImage",	answers : [Answer(answer: "By the time you finish dinner, the film will have ende", isRight : true),Answer(answer: "By the time you have finished dinner, the film will en", isRight : false),Answer(answer: "You finish dinner, and then the film will en", isRight : false),Answer(answer: "By the time you finishing dinner, the film will have ended.", isRight : false)]))
        list.append(QuestionModel(question: "A new style of jeans ________ in the U", img : "defautImage",	answers : [Answer(answer: "has just introduced", isRight : true),Answer(answer: "were just introduced", isRight : false),Answer(answer: "has just been introduced", isRight : false),Answer(answer: "have just been introduced", isRight : false)]))
        list.append(QuestionModel(question: "She ________ before I came home", img : "defautImage",	answers : [Answer(answer: "light", isRight : true),Answer(answer: "is lighting", isRight : false),Answer(answer: "had lit", isRight : false),Answer(answer: "lights", isRight : false)]))
        list.append(QuestionModel(question: "We ________ out before 10 p. m last night.", img : "defautImage",	answers : [Answer(answer: "go ", isRight : true),Answer(answer: "is going ", isRight : false),Answer(answer: "goes ", isRight : false),Answer(answer: "had gone", isRight : false)]))
        list.append(QuestionModel(question: "Lan ________ those flowers before 7 am last Monday. ", img : "defautImage",	answers : [Answer(answer: "grew ", isRight : true),Answer(answer: "had grown ", isRight : false),Answer(answer: "grow ", isRight : false),Answer(answer: "grows", isRight : false)]))
        list.append(QuestionModel(question: "The thief ________ into my house before I came home. ", img : "defautImage",	answers : [Answer(answer: "had broken ", isRight : true),Answer(answer: "breaks ", isRight : false),Answer(answer: "has broken ", isRight : false),Answer(answer: "break", isRight : false)]))
        list.append(QuestionModel(question: "He ________ in before I invited her. ", img : "defautImage",	answers : [Answer(answer: "come ", isRight : true),Answer(answer: "was coming ", isRight : false),Answer(answer: "had come ", isRight : false),Answer(answer: "came", isRight : false)]))
        list.append(QuestionModel(question: "She ________ married before she studied in university. ", img : "defautImage",	answers : [Answer(answer: "had got ", isRight : true),Answer(answer: "is getting ", isRight : false),Answer(answer: "has got ", isRight : false),Answer(answer: "got", isRight : false)]))
        list.append(QuestionModel(question: "I ________ decision before yesterday. ", img : "defautImage",	answers : [Answer(answer: "makes ", isRight : true),Answer(answer: "made ", isRight : false),Answer(answer: "has made ", isRight : false),Answer(answer: "had made", isRight : false)]))
        list.append(QuestionModel(question: "Lan ________ before I slept the day before yesterday. ", img : "defautImage",	answers : [Answer(answer: "cooked ", isRight : true),Answer(answer: "was cooking ", isRight : false),Answer(answer: "had cooked ", isRight : false),Answer(answer: "cook", isRight : false)]))
        list.append(QuestionModel(question: "I ________ ill before I came here. ", img : "defautImage",	answers : [Answer(answer: "was ", isRight : true),Answer(answer: "had been ", isRight : false),Answer(answer: "have been ", isRight : false),Answer(answer: "were", isRight : false)]))
        list.append(QuestionModel(question: "He ________ before they came. ", img : "defautImage",	answers : [Answer(answer: "win ", isRight : true),Answer(answer: "was winning ", isRight : false),Answer(answer: "won ", isRight : false),Answer(answer: "had won", isRight : false)]))
        list.append(QuestionModel(question: "He ________ the truth before they forced him. ", img : "defautImage",	answers : [Answer(answer: "told ", isRight : true),Answer(answer: "is telling ", isRight : false),Answer(answer: "had told ", isRight : false),Answer(answer: "has told", isRight : false)]))
        list.append(QuestionModel(question: "He ________ my money before I hint it. ", img : "defautImage",	answers : [Answer(answer: "had stolen ", isRight : true),Answer(answer: "is stealing ", isRight : false),Answer(answer: "has stolen ", isRight : false),Answer(answer: "will steal", isRight : false)]))
        list.append(QuestionModel(question: "My father ________ his work before lunch time. ", img : "defautImage",	answers : [Answer(answer: "finished ", isRight : true),Answer(answer: "had finished ", isRight : false),Answer(answer: "finish ", isRight : false),Answer(answer: "will finish", isRight : false)]))
        list.append(QuestionModel(question: "John ________ away before his parents punished him. ", img : "defautImage",	answers : [Answer(answer: "went ", isRight : true),Answer(answer: "is going ", isRight : false),Answer(answer: "has gone ", isRight : false),Answer(answer: "had gone", isRight : false)]))
        list.append(QuestionModel(question: "Yesterday If I ________ her, I would have helped her a lot. ", img : "defautImage",	answers : [Answer(answer: "had known ", isRight : true),Answer(answer: "is knowing ", isRight : false),Answer(answer: "has known ", isRight : false),Answer(answer: "knew", isRight : false)]))
        list.append(QuestionModel(question: "The party chairman only _______a statement after there _______ a lot of speculation in the press. ", img : "defautImage",	answers : [Answer(answer: "makes / had been ", isRight : true),Answer(answer: "made / had been ", isRight : false),Answer(answer: "had made / will be ", isRight : false),Answer(answer: "was making / was", isRight : false)]))
        list.append(QuestionModel(question: "Helen _______ hospital treatment for a year before the doctors finally _______her their diagnosis. ", img : "defautImage",	answers : [Answer(answer: "will receive / is telling ", isRight : true),Answer(answer: "had received / told", isRight : false),Answer(answer: "receive / tell ", isRight : false),Answer(answer: "received / had told", isRight : false)]))
        list.append(QuestionModel(question: "Sharon eventually ________ the job she ________ last year, although she ________ the year before. ", img : "defautImage",	answers : [Answer(answer: "finds / wants/ graduates ", isRight : true),Answer(answer: "found / wanted/ had graduated", isRight : false),Answer(answer: "found / wanted/ graduated ", isRight : false),Answer(answer: "finds / had wanted/ graduated", isRight : false)]))
        list.append(QuestionModel(question: "When the doctors________ at the scene of the accident, they ________ victims still ________. ", img : "defautImage",	answers : [Answer(answer: "arrived / realized / were breathing ", isRight : true),Answer(answer: "were arriving / realized / breathed", isRight : false),Answer(answer: "arrived / had realized / breathed ", isRight : false),Answer(answer: "were arriving / were realizing / were breathing", isRight : false)]))
        list.append(QuestionModel(question: "I suddenly ________ the Tower Square. I ________ there ten years before. ", img : "defautImage",	answers : [Answer(answer: "recognized / was ", isRight : true),Answer(answer: "was recognizing / was", isRight : false),Answer(answer: "recognized / had been ", isRight : false),Answer(answer: "had recognized / had", isRight : false)]))
        list.append(QuestionModel(question: "Nam ________ smoking two years ago. ", img : "defautImage",	answers : [Answer(answer: "stops ", isRight : true),Answer(answer: "has stopped ", isRight : false),Answer(answer: "stopped ", isRight : false),Answer(answer: "is stopping ", isRight : false)]))
        list.append(QuestionModel(question: "They ________ in our country since January, 1st 2002. ", img : "defautImage",	answers : [Answer(answer: "are ", isRight : true),Answer(answer: "have been ", isRight : false),Answer(answer: "were ", isRight : false),Answer(answer: "had been", isRight : false)]))
        list.append(QuestionModel(question: "Lan: I work for a big company. ? Lan said she________ for a big company. ", img : "defautImage",	answers : [Answer(answer: "had worked ", isRight : true),Answer(answer: "work ", isRight : false),Answer(answer: "worked ", isRight : false),Answer(answer: "is working", isRight : false)]))
        list.append(QuestionModel(question: "He started working as a teacher five years ago. ", img : "defautImage",	answers : [Answer(answer: "He has been working as a teacher for five years. ", isRight : true),Answer(answer: "He has worked as a teacher since five years. ", isRight : false),Answer(answer: "He is working as a teacher since five years. ", isRight : false),Answer(answer: "He had been working as a teacher for five years ", isRight : false)]))
        list.append(QuestionModel(question: "After he ________ his English course, he went to England to continue his study. ", img : "defautImage",	answers : [Answer(answer: "has finished ", isRight : true),Answer(answer: "had finished ", isRight : false),Answer(answer: "was finished ", isRight : false),Answer(answer: "would finish", isRight : false)]))
        list.append(QuestionModel(question: "The Browns_______ here since 1990. ", img : "defautImage",	answers : [Answer(answer: "live ", isRight : true),Answer(answer: "are living ", isRight : false),Answer(answer: "have lived ", isRight : false),Answer(answer: "had lived", isRight : false)]))
        list.append(QuestionModel(question: "I wish I _______ all about this some weeks ago. ", img : "defautImage",	answers : [Answer(answer: "knew ", isRight : true),Answer(answer: "have known ", isRight : false),Answer(answer: "had known ", isRight : false),Answer(answer: "would know", isRight : false)]))
        list.append(QuestionModel(question: "He said that he _______ his bicycle the night before. ", img : "defautImage",	answers : [Answer(answer: "has lost ", isRight : true),Answer(answer: "loses ", isRight : false),Answer(answer: "had lost ", isRight : false),Answer(answer: "lost", isRight : false)]))
        list.append(QuestionModel(question: "As the sun _________ , I decided to go out. ", img : "defautImage",	answers : [Answer(answer: "shines ", isRight : true),Answer(answer: "has shine ", isRight : false),Answer(answer: "shine ", isRight : false),Answer(answer: "was shining", isRight : false)]))
        list.append(QuestionModel(question: "By the time the police arrive, the thieves________ the stolen things. ", img : "defautImage",	answers : [Answer(answer: "hide ", isRight : true),Answer(answer: "had hidden ", isRight : false),Answer(answer: "are hiding ", isRight : false),Answer(answer: "will have hidden", isRight : false)]))
        list.append(QuestionModel(question: "She came into the room while they _______ television", img : "defautImage",	answers : [Answer(answer: "have watched ", isRight : true),Answer(answer: "watched ", isRight : false),Answer(answer: "have been watching ", isRight : false),Answer(answer: "were watching", isRight : false)]))
        list.append(QuestionModel(question: "The baby_________ non-stop for half an hour. ", img : "defautImage",	answers : [Answer(answer: "cried ", isRight : true),Answer(answer: "is crying ", isRight : false),Answer(answer: "has been crying ", isRight : false),Answer(answer: "was crying", isRight : false)]))
        list.append(QuestionModel(question: "Mr. Smith said he would come but he_________ yet. ", img : "defautImage",	answers : [Answer(answer: "did not come ", isRight : true),Answer(answer: "had not come ", isRight : false),Answer(answer: "does not come ", isRight : false),Answer(answer: "has not come", isRight : false)]))
        list.append(QuestionModel(question: "By the time we get out of this traffic jam, all the guests _______ home. ", img : "defautImage",	answers : [Answer(answer: "have gone ", isRight : true),Answer(answer: "had gone ", isRight : false),Answer(answer: "will go ", isRight : false),Answer(answer: "will have gone", isRight : false)]))
        list.append(QuestionModel(question: "All the guests _______ home by the time you come to the party. ", img : "defautImage",	answers : [Answer(answer: "have gone ", isRight : true),Answer(answer: "had gone ", isRight : false),Answer(answer: "will go ", isRight : false),Answer(answer: "will have gone", isRight : false)]))
        list.append(QuestionModel(question: "Sorry. I can`t go there with you now. I _________ my homework at present. ", img : "defautImage",	answers : [Answer(answer: "did ", isRight : true),Answer(answer: "do ", isRight : false),Answer(answer: "was doing ", isRight : false),Answer(answer: "am doing", isRight : false)]))
        list.append(QuestionModel(question: "She always _________ dates on the holidays. ", img : "defautImage",	answers : [Answer(answer: "have ", isRight : true),Answer(answer: "had ", isRight : false),Answer(answer: "has had ", isRight : false),Answer(answer: "has", isRight : false)]))
        list.append(QuestionModel(question: "Last year, they _________ to Europe with their best friends on their summer holidays. ", img : "defautImage",	answers : [Answer(answer: "visited ", isRight : true),Answer(answer: "traveled ", isRight : false),Answer(answer: "will travel ", isRight : false),Answer(answer: "are visiting", isRight : false)]))
        list.append(QuestionModel(question: "What are you going to do this weekend?- We _______ visit our grandfather in the countryside. ", img : "defautImage",	answers : [Answer(answer: "are going to ", isRight : true),Answer(answer: "were going to ", isRight : false),Answer(answer: "have gone to ", isRight : false),Answer(answer: "went", isRight : false)]))
        list.append(QuestionModel(question: "Our Singaporean friends_______________ to visit our school last year. ", img : "defautImage",	answers : [Answer(answer: "is coming ", isRight : true),Answer(answer: "come ", isRight : false),Answer(answer: "came ", isRight : false),Answer(answer: "have come", isRight : false)]
            ))

      }
}
